phabricator:
  build: .
  command: run
  ports:
    # Port for sshd_ctrl, !! NEVER EXPOSE TO PUBLIC !!
    - "127.0.0.1:2201:222"
    # Port for sshd_vcs
    - "2200:22"
    # Port for aphlict
    - "22280:22280"
    # Port for nginx
    - "80:80"
  volumes:
    # Volumes for repos
    - "/data/repos:/srv/repos"
    # Volumes for uploaded files
    - "/data/uploads:/srv/uploads"
    # Volumes for pre-configurations
    - "/data/pre:/srv/pre"
    # Volumes for sshd_keys
    - "/data/sshd_keys:/srv/etc/sshd_keys"
    # Volumes for logging and pids
    - "/data/run:/srv/run"
  links:
    - "mysql:mysql"
mysql:
  image: mysql
  volumes:
    # MySQL data
    - "/data/mysql:/var/lib/mysql"
    # MySQL configuration
    - "/data/mysql_conf:/etc/mysql/conf.d"
  environment:
    MYSQL_ROOT_PASSWORD: some-random-password
